### ISSUE TITLE
Deleting False Positives

### ISSUE THREAD

**Issue by ldfelipe** [UTMediaCAT/Voyage#1]
what happens when you delete a false positive, will the article keep coming up if I delete it? I ask because articles about Gwyneth Paltrow are being included when the crawl is running because the keyword "YNET" is part of her name. Should I go ahead an manually delete these articles as it crawls?

**Comment by Sunakujira1** [comment]
Currently, we do not keep record of the deleted article, thus it will keep coming up even if you delete those articles.
We are planning to make the keyword matching part more strict (ie. no letters before and after the keyword) to avoid these problems, whereas we haven't discussed about keeping records of removed articles as blacklist in future.

**Comment by Sunakujira1** [comment]
The stricter algorithm have been patched at e39c2b987689704091a59aa3f85a6f87bc2e32dc. You can go ahead and delete those articles, since the case you've specified should be ignored from now on.
