### ISSUE TITLE
Twitter Statistics Google Chart Broken

### ISSUE THREAD

**Issue by paulkirow** [UTMediaCAT/Voyage#13]
The chart does not display any data, only shows this:

Data must contain at least two columns.

http://mathlab.utsc.utoronto.ca:8000/statistics/articles

**Comment by sughandj** [comment]
I will take a look into it right now

**Comment by paulkirow** [comment]
what method gets this? tweets_annotation_chart?

**Comment by sughandj** [comment]
Fixed in master, will be published live soon

**Comment by paulkirow** [comment]
There are 54 tweet citations for mondoweiss in the database.  The annotation chart shows 0,  whats up with that?

**Comment by sughandj** [comment]
mondoweiss tweets are matched only with keywords, The annotation chart is for matched sources for which no result is found yet.
I have checked the annotation chart with db of the live website on the server and it works fine.

**Comment by paulkirow** [comment]
Maybe we should update the db in the repo with some twitter citations

**Comment by sughandj** [comment]
yuya is planning to do that after a migration
