### ISSUE TITLE
Core Dumped

### ISSUE THREAD

**Issue by Sunakujira1** [UTMediaCAT/Voyage#14]
Here are some snippet of the log:
```
07/18/2015 01:58:14 AM - INFO - Finished logging config
...
2015-07-18 14:34:06 (Article|Washington Times) 2241/5526
CPU time limit exceeded (core dumped)
```
```
07/18/2015 07:45:45 PM - INFO - Finished logging config
...
2015-07-19 08:36:30 (Article|Washington Times) 2169/5528
CPU time limit exceeded (core dumped)
```
```
07/19/2015 06:02:35 PM - INFO - Finished logging config
...
2015-07-20 07:27:30 (Article|Washington Times) 2229/5519
CPU time limit exceeded (core dumped)
```

What I know until now:
* It roughly happens around 13 hours after the explorer starts.
* Several other site set as *both* are crawled without the error before this. 
* Happens always around half way through Washington Times, while Plan B.
* Twitter Explorer running concurrently has no effect.
* Memory(RES) usage are ~5% most of the times.

I think the cause is either plan B's algo or the mathlab throttling the usage.

Thoughts?

**Comment by zhouwein** [comment]
It's not plan b crashing, because if it was, it would show python style stack trace. However, it's probably caused by plan b because it scans way more pages than newspaper, which in turn causes more 100% cpu usage than newspaper. the solution would be to not use mathlab (why are we still using it again?) or put in random sleeps in the loop.

**Comment by Sunakujira1** [comment]
>However, it's probably caused by plan b because it scans way more pages than newspaper,

No, there are sites that makes newspaper itself find 5000 (max) articles, and it succeeds.  

>which in turn causes more 100% cpu usage than newspaper.

I do not have data with me, but from my experience newspaper uses 70~% whereas Plan B uses ~20% on average. Also don't forget that few sites do succeed with Plan B before the crash.

I think we are continuing to use mathlab until Alejandro acquires his own server, which will hopefully be before Fall semester starts.

**Comment by Sunakujira1** [comment]
Issue was cause of Mathlab.
