### ISSUE TITLE
Plan B

### ISSUE THREAD

**Issue by Sunakujira1** [UTMediaCAT/Voyage#15]
https://gist.github.com/Sunakujira1/3a4a6fc5fc777b6f2e32
Plan B is going over the limit and spitting error messages.
Please have a look.

**Comment by zhouwein** [comment]
obvious question: did you git pull? it looks like an issue i had while testing on my server but i pushed a commit to fix it.

**Comment by Sunakujira1** [comment]
I pulled at around 2PM and ran. I was not aware that the version I pulled on master was bugged. I pulled and restarted it.

**Comment by Sunakujira1** [comment]
```
2015-07-27 15:12:48 (Article|MSNBC) 18391/5120
```
Still going over the limit with latest on master.
