### ISSUE TITLE
twitter_explorer.py: SourceSite, SourceTwitter and CountLog model

### ISSUE THREAD

**Issue by Sunakujira1** [UTMediaCAT/Voyage#4]
SourceSite - store all links instead while assigning matched bool accordingly.
SourceTwitter - store all twitter accounts mentioned in the tweet.
CountLog - store retweet count and favorite count when visited with time stamp.

**Comment by wangx173** [comment]
SourceSite and SourceTwitter have been implemented and tested. They are working well so far. 
However, I have trouble with CountLog since tweepy doesn't really  support getting number of retweets and favourite_count

**Comment by Sunakujira1** [comment]
tweet.retweet_count and tweet.favourites_count
should be there as I can find code snippets using it. Have you tried using them?

**Comment by wangx173** [comment]
can you send me the link?  cuz tweepy says something like "up to 20 or 100"

**Comment by Sunakujira1** [comment]
[Here](http://stackoverflow.com/questions/29683447/streaming-twitter-with-tweepy-returns-retweet-count-always-0) and [here](http://stackoverflow.com/questions/16867504/tweepy-streaming-api-returning-none-for-coordinates-on-geo-enabled-tweets)
