### ISSUE TITLE
"Force Stop" Button on the top does not stop all the explorer process 

### ISSUE THREAD

**Issue by wangx173** [UTMediaCAT/Voyage#40]
need to change to something like 
kill -9 `ps -aux | grep -v grep |grep  "article_explorer.py" | awk '{ print $2 }'`

**Comment by Sunakujira1** [comment]
Deploy that fix.  
Also we should review what functionality we want.

**Comment by wangx173** [comment]
dd4e55d20b3673dd9495d992efaccd4969e5b23f fixed.
