### ISSUE TITLE
Duplicated article entry 

### ISSUE THREAD

**Issue by wangx173** [UTMediaCAT/Voyage#43]
![capture](https://cloud.githubusercontent.com/assets/8739542/11876491/fc118402-a4b7-11e5-8571-8e78ab055866.PNG)

server ip: http://159.203.7.224/admin/articles/article/?o=4.-5.3.-7&p=0

**Comment by Sunakujira1** [comment]
I am not able to login to the server.

**Comment by wangx173** [comment]
I think the server is down now.

**Comment by wangx173** [comment]
can you just search the articles manually?  since the link here is not available.
