### ISSUE TITLE
decide on software license

### ISSUE THREAD

**Issue by kimpham54** [UTMediaCAT/Voyage#49]
commercial use or not?

**Comment by kimpham54** [comment]
GPLv3 GPL grants the recipients of a computer program the rights of the Free Software Definition and uses copyleft to ensure the freedoms are preserved whenever the work is distributed, even when the work is changed or added to. The GPL is a copyleft license, which means that derived works can only be distributed under the same license terms. This is in distinction to permissive free software licenses, of which the BSD licenses and the MIT License are the standard examples. GPL was the first copyleft license for general use.

So that means that commercial use is permitted, and a fee can be charged for services, but whatever modifications are made must be made under the same license, essentially it will be free. Other features:
-patents cannot be used
-there is no warranty

The full text of the license can be found here: https://tldrlegal.com/license/gnu-general-public-license-v3-(gpl-3)#fulltext

**Comment by alejandropaz** [comment]
Here's the AGPL version:
https://tldrlegal.com/license/gnu-affero-general-public-license-v3-%28agpl-3.0%29#summary

**Comment by kimpham54** [comment]
we're deciding to go with agpl for now
