### ISSUE TITLE
plan b crawler

### ISSUE THREAD

**Issue by zhouwein** [UTMediaCAT/Voyage#5]
- [x] port plan B crawler from team15-Project
- [x] integrate crawler
- [x] add code to detect what crawler to use based on django model

**Comment by zhouwein** [comment]
Someone (preferably who worked on the model) needs to add the required code to get the crawl type from the django model and put it here: https://github.com/UTMediaCAT/Voyage/blob/crawler/src/article_explorer.py#L300

**Comment by Sunakujira1** [comment]
Some error I found while testing:
https://gist.github.com/Sunakujira1/e1478d8d2805110a392c
Site: http://alhaq.org/

**Comment by zhouwein** [comment]
apt-get install libjpeg-dev

then reinstall pillow
