### ISSUE TITLE
django secret key not randomized on installation

### ISSUE THREAD

**Issue by zhouwein** [UTMediaCAT/Voyage#53]
Currently the django SECRET_KEY is stored in the repo and not randomized upon installation. [Having a known secret key value is a security risk](https://docs.djangoproject.com/en/dev/ref/settings/#secret-key). This can be fixed by randomizing the key on installation.

**Comment by alejandropaz** [comment]
Please set up randomization.
    
    On 16/01/26 11:26 PM, zhouwein wrote:
    
    
      Currently the django SECRET_KEY is stored in the repo and not
        randomized upon installation. Having
          a known secret key value is a security risk. This can be
        fixed by randomizing the key on installation.
      —
        Reply to this email directly or view it
          on GitHub.
      
        
          
          
        
        
      
    
    
    -- 

_________________________________________________________
Alejandro I. Paz
Assistant Professor of Anthropology
University of Toronto Scarborough
Graduate Depts of Anthropology and Linguistics
University of Toronto
http://www.utsc.utoronto.ca/people/aipaz/
_________________________________________________________

**Comment by kimpham54** [comment]
see trello.
