### ISSUE TITLE
IntegrityError: null value in column "check" violates not-null constraint

### ISSUE THREAD

**Issue by wangx173** [UTMediaCAT/Voyage#65]
http://mediacat.utsc.utoronto.ca:8080/admin/explorer/referringsite/add/

IntegrityError at /admin/explorer/referringsite/add/
null value in column "check" violates not-null constraint
DETAIL:  Failing row contains (5, http://bbc.com/, hgfh, null, 0).
Request Method: POST
Request URL:    http://mediacat.utsc.utoronto.ca:8080/admin/explorer/referringsite/add/
Django Version: 1.7.1
Exception Type: IntegrityError
Exception Value:  
null value in column "check" violates not-null constraint
DETAIL:  Failing row contains (5, http://bbc.com/, hgfh, null, 0).
Exception Location: /usr/local/lib/python2.7/dist-packages/django/db/backends/utils.py in execute, line 65
Python Executable:  /usr/bin/python
Python Version: 2.7.9
Python Path:  
['/home/mediacat_test/.local/lib/python2.7/site-packages',
 '/home/mediacat_test/Voyage/Frontend',
 '/usr/lib/python2.7',
 '/usr/lib/python2.7/plat-x86_64-linux-gnu',
 '/usr/lib/python2.7/lib-tk',
 '/usr/lib/python2.7/lib-old',
 '/usr/lib/python2.7/lib-dynload',
 '/usr/local/lib/python2.7/dist-packages',
 '/usr/lib/python2.7/dist-packages',
 '/usr/lib/pymodules/python2.7',
 '../src',
 '/home/mediacat_test/Voyage/src',
 '/home/mediacat_test/Voyage/src',
 '/home/mediacat_test/Voyage/src']
Server time:    Fri, 29 Jul 2016 00:52:05 -0400

**Comment by Sunakujira1** [comment]
@wangx173 How do I access to this server?

**Comment by wangx173** [comment]
@Sunakujira1 
username:admin
pass: admin

**Comment by Sunakujira1** [comment]
I meant within the server, which directory?

**Comment by wangx173** [comment]
see the  dev_doc for more info

**Comment by wangx173** [comment]
for testing server, it is user mediacat_test
I added the server info into dev_doc,
